sudo: required

services:
  - docker

language: php

php:
  - '7.2'
  - '7.3'

env:
  - ILLUMINATE_VERSION="5"
  - ILLUMINATE_VERSION="6" REDIS_CLIENT="predis"
  - ILLUMINATE_VERSION="6" REDIS_CLIENT="phpredis"

before_install:
  - docker pull postgres:latest
  - docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 54320:5432 postgres:latest
  - docker pull mysql:latest
  - docker run --name mysql -e MYSQL_DATABASE=mysql -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_ROOT_PASSWORD=mysql -d -p 33060:3306 mysql:latest mysqld --default-authentication-plugin=mysql_native_password
  - docker pull redis:latest
  - docker run --name redis -d -p 63790:6379 redis:latest
  - mkdir -p /tmp/coverage
  - export PHP_VERSION=`php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;"`

install:
  - travis_retry composer self-update
  - composer global require hirak/prestissimo
  - cp tests/composer-illuminate-${ILLUMINATE_VERSION}.json composer.json
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-source
  - grep -v "'Redis' => " ./vendor/laravel/laravel/config/app.php > /tmp/app.php && mv /tmp/app.php ./vendor/laravel/laravel/config/app.php
  - php -m | grep redis > /dev/null || echo '' | pecl install redis > /dev/null || true
#  - COMPOSER_MEMORY_LIMIT=-1 composer require --no-interaction laravel/${ILLUMINATE_FRAMEWORK,,}:^${ILLUMINATE_VERSION}.0

script:
  - vendor/bin/phpunit --coverage-php /tmp/coverage/laravel.cov tests/LaravelTest.php
  - vendor/bin/phpunit --coverage-php /tmp/coverage/lumen.cov tests/LumenTest.php

after_success:
  - vendor/bin/phpcov merge /tmp/coverage --clover coverage.xml
  - bash <(curl -s https://codecov.io/bash)
