sudo: required

services:
  - docker

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
env:
  - ILLUMINATE_VERSION="^5.0"
  - ILLUMINATE_VERSION="^6.0" REDIS_CLIENT="predis"
  - ILLUMINATE_VERSION="^6.0" REDIS_CLIENT="phpredis"

before_install:
  - docker pull postgres:latest
  - docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 54320:5432 postgres:latest
  - docker pull mysql:latest
  - docker run --name mysql -e MYSQL_DATABASE=mysql -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_ROOT_PASSWORD=mysql -d -p 33060:3306 mysql:latest mysqld --default-authentication-plugin=mysql_native_password
  - docker pull redis:latest
  - docker run --name redis -d -p 63790:6379 redis:latest
  - mkdir -p /tmp/coverage

install:
  - travis_retry composer self-update
  - composer global require hirak/prestissimo
  - travis_retry composer require --dev --no-interaction laravel/lumen:${ILLUMINATE_VERSION}
  - travis_retry composer require --dev --no-interaction laravel/laravel:${ILLUMINATE_VERSION}
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-php /tmp/coverage/laravel.cov tests/LaravelTest.php
  - vendor/bin/phpunit --coverage-php /tmp/coverage/lumen.cov tests/LumenTest.php

after_success:
  - vendor/bin/phpcov merge /tmp/coverage --clover coverage.xml
  - bash <(curl -s https://codecov.io/bash)
